### ISSUE TITLE
Completed MVP 1 & 2

### ISSUE THREAD

**Issue by wburke415** [wburke415/GarageSale#1]
Site is hosted on heroku at thegaragesale.herokuapp.com

Finished backend and frontend user auth. Users can sign up and login, and sign out. Set up error handling for both forms.

**Comment by dwebster17** [comment]
Great job so far! Where did you find the info on `required`? It's a nice touch. Here's a few things to fix:

- [ ] Add `color: blue` to the css for your Login and Sign Up buttons. Reason being, default HTML behavior for links is that they turn purple once you've clicked them. Adding `color: blue` overrides this behavior.

- [ ] I like the Logo, its pretty funky. For recruiters sake, though, we like to keep it as simple as possible. Can you think of anything else? Maybe just a cool font (fonts.google.com) with one interesting color you like? 

- [ ] When I unsuccessfully login, errors show up. When I switch over to "Signup", those errors are still there. You should clear all errors on `componentWillUnmount`

**Comment by wburke415** [comment]
Thanks! Rose told me to look up the stuff on using require.

For adding color: blue to the buttons you mean the ones on the form right?

I'll for sure be changing the logo sometime soon. I just wanted to come up
with a quick placeholder for now at least.

Thanks for the tip on using componentWillUnmount. I had noticed that but
was blanking on how exactly I should fix it.

**Comment by dwebster17** [comment]
<img width="471" alt="screen shot 2018-08-09 at 4 49 36 pm" src="https://user-images.githubusercontent.com/29282483/43925056-3e3ae2d4-9bf4-11e8-9fde-c8007eab85c4.png">

These buttons!

**Comment by wburke415** [comment]
Ok that's what I though. They're changed to blue now.

**Comment by dwebster17** [comment]
Nice work!
